title: Mourtada.se
url: https://www.mourtada.se
name: Mourtada.se
description: I'm a developer. I love coding.

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

jekyll-crosspost_to_medium:
  enabled: false

twitter_username: jmourtada
github_username:  jontem
linkedin_username: jonathanmourtada

mastodon:
- username: jontem
  instance: mastodon.se